### ISSUE TITLE
PHP Warning in foreach() loop

### ISSUE THREAD

**Issue by tfamula-ilias** [leifos-gmbh/MantisEmailReminder#3]
Das Programm wird ohne Fehler wie gewünscht ausgeführt. Jedoch wird mehrfach folgende Warnung geworfen:

PHP Warning:  Invalid argument supplied for foreach() in ./Open_Bugs_Leifos_Tracker.php on line 82

**Comment by alex40724** [comment]
Zwei Sachen fallen mir auf

Zeile 81
            foreach ($users as $user_bugs) {
hier ist vermutlich
            foreach ($users["bugs"] as $user_bugs) {
gemeint. Die zweite Schleife kann dann wahrscheinlich entfallen.

Ich bin mir nicht sicher, ob $users["bugs"] wird nicht immer initialisiert wird (wenn es keine Bugs für den Benutzer gibt)
```
            $user_bug = array(
                "email" => $row_users["email"],
                "username" => $row_users["realname"],
                "bugs" => array()
            );
```
wäre besser. Wenn keine Bugs vorliegen, darf natürlich auch keine Mail verschickt werden.

**Comment by tfamula-ilias** [comment]
> Wenn keine Bugs vorliegen, darf natürlich auch keine Mail verschickt werden.

Dies wird verhindert durch:
`array_push($all_bugs, $user_bug);`


Alle anderen Sachen wurden gefixt.
